# Generated by Django 2.2.16 on 2020-11-17 06:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('PAYPAL', 'PAYPAL'), ('STRIPE', 'STRIPE'), ('UNITPAY', 'UNITPAY')], default='PAYPAL', max_length=100)),
                ('amount', models.CharField(default='0', max_length=10)),
                ('meta', models.TextField(blank=True, max_length=250, null=True)),
                ('payment_status', models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING'), ('FAILED', 'FAILED')], default='PENDING', max_length=100)),
                ('gateway_ref', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StripeProductMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_key', models.CharField(default='0', max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
        ),
    ]
