# Generated by Django 2.2.16 on 2022-03-26 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_activepaymentgateways'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivePaymentGateways',
            new_name='ActivePaymentGateway',
        ),
    ]
