# Generated by Django 2.2.16 on 2022-03-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20220326_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activepaymentgateway',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
