# Generated by Django 2.2.16 on 2020-11-28 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('attachment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('subject', models.CharField(choices=[('ORDER', 'ORDER'), ('PAYMENT', 'PAYMENT'), ('SERVICE', 'SERVICE'), ('CHILDPANEL', 'CHILDPANEL'), ('OTHER', 'OTHER')], default='ORDER', max_length=100)),
                ('uid', models.CharField(default='LCPKXT1', max_length=100, unique=True)),
                ('message', models.ManyToManyField(to='ticketing.Message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
