# Generated by Django 2.2.16 on 2020-12-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_auto_20201204_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uid',
            field=models.CharField(blank=True, default='57AP8FONKW', max_length=100, null=True, unique=True),
        ),
    ]
