# Generated by Django 2.2.16 on 2020-12-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_auto_20201208_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uid',
            field=models.CharField(blank=True, default='L9ZB4ICKL6', max_length=100, null=True, unique=True),
        ),
    ]
