# Generated by Django 2.2.16 on 2021-12-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_auto_20201208_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uid',
            field=models.CharField(blank=True, default='TP0M94OF31', max_length=100, null=True, unique=True),
        ),
    ]
