# Generated by Django 2.2.16 on 2021-12-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_auto_20211202_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uid',
            field=models.CharField(blank=True, default='CGC9CVRLHA', max_length=100, null=True, unique=True),
        ),
    ]
