# Generated by Django 2.2.16 on 2021-12-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_auto_20211205_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uid',
            field=models.CharField(blank=True, default='CVTXR45STA', max_length=100, null=True, unique=True),
        ),
    ]
