# Generated by Django 2.2.16 on 2021-12-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_auto_20211207_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uid',
            field=models.CharField(blank=True, default='HZ9XVMOXFB', max_length=100, null=True, unique=True),
        ),
    ]
