# Generated by Django 2.2.16 on 2021-12-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0009_auto_20211207_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uid',
            field=models.CharField(blank=True, default='ENKOOCCLTY', max_length=100, null=True, unique=True),
        ),
    ]
