# Generated by Django 2.2.16 on 2021-12-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0010_auto_20211218_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uid',
            field=models.CharField(blank=True, default='PF5MDSJ6AE', max_length=100, null=True, unique=True),
        ),
    ]
