# Generated by Django 2.2.16 on 2021-12-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0011_auto_20211219_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uid',
            field=models.CharField(blank=True, default='3C5L4RM92A', max_length=100, null=True, unique=True),
        ),
    ]
