# Generated by Django 2.2.16 on 2021-12-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0014_auto_20211219_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uid',
            field=models.CharField(blank=True, default='C3M02ALJ5Q', max_length=100, null=True, unique=True),
        ),
    ]
