# Generated by Django 2.2.16 on 2021-12-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0015_auto_20211219_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uid',
            field=models.CharField(blank=True, default='PSH56NZX2P', max_length=100, null=True, unique=True),
        ),
    ]
