# Generated by Django 2.2.16 on 2022-03-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0017_auto_20211219_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
