# Generated by Django 2.2.16 on 2022-03-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
