# Generated by Django 2.2.16 on 2022-03-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20220303_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='faq',
        ),
        migrations.AddField(
            model_name='service',
            name='faq',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='services.FAQ'),
        ),
    ]
