# Generated by Django 2.2.16 on 2022-03-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20220303_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='faq',
            new_name='faqs',
        ),
    ]
