# Generated by Django 2.2.16 on 2022-03-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20220305_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='link_regex_validate',
            field=models.TextField(blank=True),
        ),
    ]
