# Generated by Django 2.2.16 on 2022-03-12 20:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_service_link_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='seo_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='seo_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='seo_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
