# Generated by Django 2.2.16 on 2022-03-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20220312_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='faqs',
            field=models.ManyToManyField(blank=True, default=None, to='services.FAQ'),
        ),
    ]
