# Generated by Django 2.2.16 on 2022-03-21 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_platform_faqs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='api',
            new_name='api_order_create',
        ),
    ]
