# Generated by Django 2.2.16 on 2022-03-21 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_auto_20220321_0716'),
        ('services', '0013_auto_20220321_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='api_order_status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_order_status', to='vendors.VendorApi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='api_order_create',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_order_create', to='vendors.VendorApi'),
        ),
    ]
