# Generated by Django 2.2.16 on 2022-03-21 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_auto_20220321_0716'),
        ('services', '0014_auto_20220321_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='api_order_refill',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_order_refill', to='vendors.VendorApi'),
        ),
    ]
