# Generated by Django 2.2.16 on 2020-10-31 09:17

import bitfield.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(max_length=40, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=100, unique=True)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('picture_url', models.CharField(blank=True, max_length=200)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('flags', bitfield.models.BitField(('is_seller', 'is_buyer', 'is_staff'), blank=True, default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
