# Generated by Django 2.2.16 on 2020-11-01 09:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(blank=True, max_length=50)),
                ('parameter_type', models.CharField(blank=True, max_length=50)),
                ('value', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('main_url', models.CharField(blank=True, max_length=100)),
                ('api_base', models.CharField(blank=True, max_length=200)),
                ('api_key', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('api_name', models.CharField(blank=True, max_length=200)),
                ('api_url', models.CharField(blank=True, max_length=250)),
                ('api_type', models.CharField(choices=[('ORDERS_PLACE', 'ORDERS_PLACE'), ('ORDERS_STATUS', 'ORDERS_STATUS'), ('MULTI_ORDERS_STATUS', 'MULTI_ORDERS_STATUS'), ('MULTI_ORDERS_STATUS', 'MULTI_ORDERS_STATUS'), ('CREATE_REFILL', 'CREATE_REFILL'), ('REFILL_STATUS', 'REFILL_STATUS'), ('USER_BALANCE', 'USER_BALANCE')], default='ORDERS_PLACE', max_length=100)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('UPDATE', 'UPDATE')], default='GET', max_length=50)),
                ('parameters', models.ManyToManyField(to='vendors.RequestParameters')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
