# Generated by Django 2.2.16 on 2022-03-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_responseparameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorapi',
            name='response_params',
            field=models.ManyToManyField(to='vendors.ResponseParameters'),
        ),
    ]
