# Generated by Django 2.2.16 on 2022-03-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendorapi_response_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorapi',
            name='api_type',
            field=models.CharField(choices=[('ORDERS_PLACE', 'ORDERS_PLACE'), ('ORDERS_STATUS', 'ORDERS_STATUS'), ('MULTI_ORDERS_STATUS', 'MULTI_ORDERS_STATUS'), ('CREATE_REFILL', 'CREATE_REFILL'), ('REFILL_STATUS', 'REFILL_STATUS'), ('USER_BALANCE', 'USER_BALANCE')], default='ORDERS_PLACE', max_length=100),
        ),
    ]
