# Generated by Django 2.2.16 on 2020-11-03 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('COMPLETED', 'PROCESSING'), ('FAILED', 'FAILED')], default='COMPLETED', max_length=50)),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
