# Generated by Django 2.2.16 on 2022-03-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_varient'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='response_raw',
            field=models.TextField(blank=True, null=True),
        ),
    ]
