# Generated by Django 2.2.16 on 2022-03-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_response_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('PROCESSING', 'PROCESSING'), ('FAILED', 'FAILED'), ('PENDING', 'PENDING'), ('CANCELLED', 'CANCELLED'), ('IN PROGRESS', 'IN_PROGRESS'), ('PARTIAL', 'PARTIAL')], default='PENDING', max_length=50),
        ),
    ]
