# Generated by Django 2.2.16 on 2022-03-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20220304_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='IaCSzk8mxDW3JV1VsrKom', max_length=100, unique=True),
        ),
    ]
