# Generated by Django 2.2.16 on 2022-03-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20220316_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='CSsiPjpOGEDP6wdm_1g-d', max_length=100, unique=True),
        ),
    ]
