# Generated by Django 2.2.16 on 2022-03-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='8gBib5jR4O', max_length=100, null=True, unique=True),
        ),
    ]
