# Generated by Django 2.2.16 on 2022-03-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='vHSHr2sJ2_', max_length=100, null=True),
        ),
    ]
