# Generated by Django 2.2.16 on 2022-03-21 01:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20220320_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('order_id', models.CharField(blank=True, default='iFgA2lNQnh', max_length=100, null=True)),
                ('last_checked', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='iFgA2lNQnh', max_length=100, null=True),
        ),
    ]
