# Generated by Django 2.2.16 on 2022-03-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20220324_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='order_id',
        ),
    ]
