# Generated by Django 2.2.16 on 2022-03-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20220324_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statuscheck',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
