# Generated by Django 2.2.16 on 2022-05-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20220324_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_visible_status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('PROCESSING', 'PROCESSING'), ('FAILED', 'FAILED'), ('PENDING', 'PENDING'), ('CANCELLED', 'CANCELLED'), ('IN PROGRESS', 'IN_PROGRESS'), ('PARTIAL', 'PARTIAL')], default='PENDING', max_length=50),
        ),
    ]
